language: java
jdk:
  - openjdk11
  - openjdk16
os:
  - linux
  - osx
  #- windows
install: true



before_script:
  - pip install --user codecov

script: ./mvnw clean verify
deploy:
  provider: script
  script: .travis/release.sh
  cleanup: false
  on:
    tags: true
    jdk: openjdk11
    os: linux
after_success:
  - codecov

