language: java
jdk:
  - openjdk11
  - openjdk16
os:
  - linux
  - osx
  #- windows
install: true
before_cache:
  - rm -f  $HOME/.m2/
cache:
  directories:
    - $HOME/.m2/

before_script:
  - pip install --user codecov

after_success:
  - codecov

